# Generated by Django 2.0 on 2021-12-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20211220_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestabinaria',
            name='votacionBinaria',
        ),
        migrations.AddField(
            model_name='question',
            name='yes_no_question',
            field=models.BooleanField(default=False, help_text='Check the box to generate automatically the options yes/no ', verbose_name='Yes/No question'),
        ),
        migrations.DeleteModel(
            name='RespuestaBinaria',
        ),
        migrations.DeleteModel(
            name='VotacionBinaria',
        ),
    ]
