# Generated by Django 2.0 on 2022-01-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20211220_2225'),
        ('voting', '0006_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
    ]
