# Generated by Django 2.0 on 2022-01-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_merge_20220104_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detector',
        ),
        migrations.DeleteModel(
            name='Percentage',
        ),
    ]
