# Generated by Django 2.0 on 2022-01-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_merge_20220104_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='binary_question',
        ),
    ]
