# Generated by Django 2.0 on 2022-01-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20220104_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='YNNS_question',
            field=models.BooleanField(default=False, help_text='Check the box to create a question of Yes, No or NS/NC', verbose_name='Answers Yes, No, NS/NC'),
        ),
    ]
