# Generated by Django 2.0 on 2022-01-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_merge_20220103_1820'),
        ('voting', '0009_question_ynns_question'),
    ]

    operations = [
    ]
