# Generated by Django 2.0 on 2022-01-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_merge_20220105_1639'),
        ('voting', '0007_merge_20220104_1613'),
    ]

    operations = [
    ]
