# Generated by Django 2.0 on 2021-12-20 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingcount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
