# Generated by Django 2.0 on 2021-12-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roll',
        ),
    ]
