# Generated by Django 2.0 on 2021-12-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='rol',
            name='title',
            field=models.CharField(choices=[('CLIENT', 'CLIENT'), ('SELLER', 'SELLER')], default='CLIENT', max_length=6),
        ),
    ]
